#!/bin/bash

sudo apt update
sudo apt-get update

sudo apt-get install dnsmasq hostapd
#sudo apt install nodejs

curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs

sudo git clone https://github.com/Vochsel/GameHub-Server.git
cd GameHub-Server

npm install
npm update